import { test, expect } from '@playwright/test';
import {
  launchVSCode,
  closeVSCode,
  screenshot,
  injectCursorOverlay,
  clickInFrame,
  resetLog,
  log,
  logCheck,
  type VSCodeApp,
} from '../utils/vscode';
import {
  setupMainPanel,
  setUrlAndSend,
  waitForResponse,
  openCodegen,
  closeCodegen,
  mockUrl,
} from '../utils/helpers';
import type { Frame } from '@playwright/test';

const LANGUAGES = [
  'cURL',
  'JavaScript (fetch)',
  'JavaScript (axios)',
  'Node.js (node-fetch)',
  'Python (requests)',
  'Java (OkHttp)',
  'Swift (URLSession)',
  'Go (net/http)',
  'PowerShell',
  'PHP (cURL)',
  'C# (HttpClient)',
];

let app: VSCodeApp;
let mainFrame: Frame | null = null;

test.describe('Code Generation', () => {
  test.describe.configure({ mode: 'serial' });

  test.beforeAll(async () => {
    resetLog();
    log('=== [Codegen] beforeAll ===');
    app = await launchVSCode();
    await injectCursorOverlay(app.window);
    mainFrame = await setupMainPanel(app);
    log('=== [Codegen] setup complete ===');
  });

  test.afterAll(async () => {
    log('=== [Codegen] afterAll ===');
    await closeVSCode(app);
  });

  test('Setup: send a request so codegen has data', async () => {
    log('--- Setup request ---');
    await setUrlAndSend(mainFrame!, mockUrl('/'));
    const ok = await waitForResponse(mainFrame!, 15_000);
    expect(ok).toBe(true);
    log('Request completed for codegen');
  });

  test('Open codegen modal', async () => {
    log('--- Open codegen ---');
    await openCodegen(mainFrame!);
    const modal = mainFrame!.locator('[data-testid="codegen-modal"]');
    const visible = await modal.isVisible().catch(() => false);
    logCheck('Codegen modal visible', visible);
    expect(visible).toBe(true);
    await screenshot(app.window, 'codegen-open');
  });

  test('All 11 languages are present', async () => {
    log('--- Verify languages ---');
    const modal = mainFrame!.locator('[data-testid="codegen-modal"]');
    const text = (await modal.textContent().catch(() => '')) ?? '';

    for (const lang of LANGUAGES) {
      const found = text.includes(lang);
      logCheck(`Language: ${lang}`, found);
      expect(found).toBe(true);
    }
  });

  test('cURL code is generated by default', async () => {
    log('--- cURL default ---');
    const modal = mainFrame!.locator('[data-testid="codegen-modal"]');
    const text = (await modal.textContent().catch(() => '')) ?? '';
    logCheck('cURL code generated', text.includes('curl'));
    expect(text).toContain('curl');
  });

  for (const lang of LANGUAGES) {
    test(`Generate code for ${lang}`, async () => {
      log(`--- Generate ${lang} ---`);
      const modal = mainFrame!.locator('[data-testid="codegen-modal"]');

      // Find and click the language button
      const langBtns = modal.locator('button, div[role="button"], li, div').filter({ hasText: lang });
      if (await langBtns.count() > 0) {
        await langBtns.first().click();
        await mainFrame!.waitForTimeout(300);
      }

      // Verify code block has content
      const codeBlock = modal.locator('[role="region"]').first();
      const codeText = (await codeBlock.textContent().catch(() => '')) ?? '';
      const hasCode = codeText.length > 10;
      logCheck(`${lang} code generated`, hasCode);
      expect(hasCode).toBe(true);

      await screenshot(app.window, `codegen-${lang.replace(/[^a-zA-Z]/g, '-').toLowerCase()}`);
    });
  }

  test('Close codegen modal', async () => {
    log('--- Close codegen ---');
    await closeCodegen(mainFrame!);
    const modal = mainFrame!.locator('[data-testid="codegen-modal"]');
    const stillVisible = await modal.isVisible().catch(() => false);
    logCheck('Modal closed', !stillVisible);
    expect(stillVisible).toBe(false);
  });
});
