import * as vscode from "vscode";
import * as os from "os";
import { StorageManager } from "../storage/StorageManager";
import { getMainPanelHtml } from "../webview/mainPanelHtml";
import { ActivityProvider } from "./ActivityProvider";
import {
  errorMsg,
  getOAuth2Token,
  oauth2CacheKey,
  type OAuth2Config,
} from "../core";
import {
  parsePostmanEnvironment,
  parseRestifyEnvironment,
  environmentToPostman,
} from "../core/converters";
import { showOpenDialog, showSaveDialog } from "./dialogStub";
import { runScriptAndReport } from "./scriptRunner";
import { WsSessionManager } from "./WsSessionManager";
import { RequestData } from "./requestTypes";
import { RequestExecutor } from "./RequestExecutor";
import {
  downloadFile,
  initializeProxySettings,
  saveResponseToFile,
} from "./restifyPanelUtils";

export class RestifyPanel {
  private panel: vscode.WebviewPanel;
  private context: vscode.ExtensionContext;
  private storageManager: StorageManager;
  private onDispose: (instance: RestifyPanel) => void;
  private activityProvider?: ActivityProvider;
  private requestExecutor: RequestExecutor;
  private pendingRequest: RequestData | null = null;
  private webviewReady: boolean = false;
  private pendingRequestFetch: ((request: any) => void) | null = null;
  private wsSessions: WsSessionManager;
  private readonly extensionVersion: string;
  /** Window session id (generated by the webview and set on its window). Chain
   *  variables are scoped to it; a new window gets a new id → scope terminates. */
  private sessionId: string = "";

  constructor(
    context: vscode.ExtensionContext,
    storageManager: StorageManager,
    onDispose: (instance: RestifyPanel) => void,
    activityProvider?: ActivityProvider,
  ) {
    this.context = context;
    this.storageManager = storageManager;
    this.onDispose = onDispose;
    this.activityProvider = activityProvider;
    this.extensionVersion =
      this.context.extension.packageJSON?.version || "dev";

    this.panel = vscode.window.createWebviewPanel(
      "restify-main",
      "New Request",
      vscode.ViewColumn.One,
      {
        enableScripts: true,
        retainContextWhenHidden: true,
        localResourceRoots: [context.extensionUri],
      },
    );

    this.panel.webview.html = getMainPanelHtml(context, this.panel.webview);
    this.wsSessions = new WsSessionManager(
      (message) => this.panel.webview.postMessage(message),
      (raw) => this.storageManager.resolveVariables(raw),
    );
    this.panel.webview.onDidReceiveMessage((msg) => {
      if (msg?.sessionId) this.sessionId = msg.sessionId;
      this._handleMessage(msg).catch((err) => {
        console.error("Error handling message:", err);
        // Send error response to webview to clear loading state
        this.panel.webview.postMessage({
          command: "requestError",
          error: err?.message || "An unexpected error occurred",
          duration: 0,
        });
      });
    });

    this.panel.onDidDispose(() => {
      this.wsSessions.closeAll();
      if (this.sessionId) this.storageManager.clearSessionChainVars(this.sessionId);
      this.onDispose(this);
    });

    // Post theme kind and listen for changes so webview can adapt icon coloring
    try {
      this.panel.webview.postMessage({
        command: "setTheme",
        kind: vscode.window.activeColorTheme.kind,
      });
    } catch {
      /* empty */
    }
    const themeListener = vscode.window.onDidChangeActiveColorTheme((t) => {
      this.panel.webview.postMessage({ command: "setTheme", kind: t.kind });
    });
    this.panel.onDidDispose(() => themeListener.dispose());

    this.requestExecutor = new RequestExecutor({
      postMessage: (message) => this.panel.webview.postMessage(message),
      storage: storageManager,
      activity: activityProvider,
      extensionVersion: this.extensionVersion,
      getSessionId: () => this.sessionId,
      onSetVariables: (variables) =>
        this._handleMessage({ command: "setScriptVariables", variables }),
    });

    this.updateMetadata();
  }

  updateMetadata(): void {
    // Small delay to ensure webview is ready to receive messages
    setTimeout(() => {
      this._sendEnvironments();
      this.panel.webview.postMessage({
        command: "collections",
        data: this.storageManager.getCollections(),
      });
      const settings = this.storageManager.getSettings();
      this.panel.webview.postMessage({
        command: "loadSettings",
        settings,
      });
      // Sync activity log enabled state
      this.activityProvider?.setEnabled(settings.showActivityLog !== false);
    }, 100);
  }

  loadRequest(requestData: RequestData): void {
    this.pendingRequest = requestData;

    if (requestData && requestData.name) {
      this.panel.title = requestData.name;
    }

    // If webview is already ready, send immediately
    if (this.webviewReady) {
      this._sendPendingRequest();
    }
  }

  sendRequest(): void {
    if (this.webviewReady) {
      this.panel.webview.postMessage({ command: 'triggerSendRequest' });
    }
  }

  /** Ask the webview for its current request state (used by exports). */
  getCurrentRequest(): Promise<any> {
    return new Promise((resolve) => {
      if (!this.webviewReady) {
        resolve(this.pendingRequest);
        return;
      }
      this.pendingRequestFetch = resolve;
      this.panel.webview.postMessage({ command: 'getCurrentRequest', id: 'export' });
    });
  }

  private _sendPendingRequest(): void {
    if (this.pendingRequest) {
      this.panel.webview.postMessage({
        command: "loadRequest",
        data: this.pendingRequest,
      });
      this.pendingRequest = null;
    }
  }

  private _sendEnvironments(): void {
    this.panel.webview.postMessage({
      command: "setEnvironments",
      environments: this.storageManager.getEnvironments(),
      activeEnvId: this.storageManager.getActiveEnvironment()?.id || null,
    });
  }

  /** Push the window session's chain variables so the webview can render
   *  `{{var}}` tokens as resolved (with hover values). */
  private _sendSessionChainVars(): void {
    if (!this.sessionId) return;
    try {
      this.panel.webview.postMessage({
        command: "sessionChainVarsUpdated",
        variables: this.storageManager.getSessionChainVars(this.sessionId),
      });
    } catch {
      /* ignore */
    }
  }

  // F44: Import an environment from a Postman or Restify environment JSON file.
  private async _importEnvironment(): Promise<void> {
    const uris = await showOpenDialog({
      canSelectMany: false,
      filters: { "Environment (Postman / Restify JSON)": ["json"] },
      openLabel: "Import Environment",
    });
    if (!uris || !uris[0]) return;
    const raw = Buffer.from(
      await vscode.workspace.fs.readFile(uris[0]),
    ).toString("utf8");

    let data: any;
    try {
      data = JSON.parse(raw);
    } catch {
      vscode.window.showErrorMessage("Import failed: file is not valid JSON.");
      return;
    }
    const imported = parsePostmanEnvironment(data) || parseRestifyEnvironment(data);
    if (!imported) {
      vscode.window.showErrorMessage(
        "Import failed: not a recognized Postman or Restify environment file.",
      );
      return;
    }
    await this.storageManager.saveEnvironment({
      id: "",
      name: imported.name,
      variables: imported.variables.map((v) => ({
        key: v.key,
        value: v.value,
        isSecret: v.isSecret, initialValue: v.initialValue,
      })),
    });
    this._sendEnvironments();
    vscode.window.showInformationMessage(
      `\u2713 Imported environment "${imported.name}"`,
    );
  }

  // F44: Export an environment as a Postman environment JSON file.
  private async _exportEnvironment(env: any): Promise<void> {
    if (!env || !env.name) return;
    const safe =
      env.name
        .toLowerCase()
        .replace(/[^a-z0-9._-]/gi, "-")
        .replace(/-+/g, "-")
        .replace(/(^-|-$)/g, "") || "environment";
    const uri = await showSaveDialog({
      defaultUri: vscode.Uri.joinPath(
        vscode.workspace.workspaceFolders?.[0]?.uri ||
          vscode.Uri.file(os.homedir()),
        `${safe}.postman_environment.json`,
      ),
      filters: { "Postman Environment JSON": ["json"] },
    });
    if (!uri) return;
    const out = environmentToPostman({
      name: env.name,
      variables: (env.variables || []).map((v: any) => ({
        key: v.key,
        value: v.value || "",
        isSecret: !!v.isSecret,
      })),
    });
    await vscode.workspace.fs.writeFile(
      uri,
      Buffer.from(JSON.stringify(out, null, 2), "utf8"),
    );
    vscode.window.showInformationMessage(
      `\u2713 Environment exported to ${uri.fsPath}`,
    );
  }

  private async _handleGetOAuthToken(config: OAuth2Config, tabId = "tab-1"): Promise<void> {
    const postResult = (payload: Record<string, unknown>) => {
      this.panel.webview.postMessage({ command: "oauthTokenResult", tabId, ...payload });
    };
    try {
      const result = await getOAuth2Token(config, {
        cache: {
          get: (key) => this.storageManager.getOAuthTokenCache(key),
          set: (key, token) => this.storageManager.setOAuthTokenCache(key, token),
        },
        cacheKey: oauth2CacheKey(config),
        openUrl: (url) => {
          if (process.env.RESTIFY_TEST_OPEN_URL === "fetch") {
            // Test hook: perform the redirect server-side instead of opening a
            // browser (the mock auth server 302-redirects to the loopback).
            void fetch(url).catch((err) => {
              console.error("OAuth test openUrl fetch failed:", err);
            });
            return;
          }
          void vscode.env.openExternal(vscode.Uri.parse(url));
          this.activityProvider?.append(
            "OAuth 2.0",
            `Opening browser for authorization:\n${url}`,
            "info",
          );
        },
        log: (message) =>
          this.activityProvider?.append("OAuth 2.0", message, "info"),
      });
      postResult({
        accessToken: result.token.accessToken,
        refreshToken: result.token.refreshToken,
        expiresAt: result.token.expiresAt,
        tokenType: result.token.tokenType,
        scope: result.token.scope,
        source: result.source,
      });
    } catch (err) {
      const message = errorMsg(err);
      this.activityProvider?.append("OAuth 2.0", `Error: ${message}`, "error");
      postResult({ error: message });
    }
  }

  private async _handleMessage(msg: any): Promise<void> {
    switch (msg.command) {
      case "webviewReady":
        // Webview is ready, send all initial data
        this.webviewReady = true;
        this.updateMetadata();
        // Send any pending request data
        this._sendPendingRequest();
        // Sync any existing chain variables into the freshly-loaded window
        this._sendSessionChainVars();
        break;
      case "currentRequest":
        if (this.pendingRequestFetch) {
          const resolve = this.pendingRequestFetch;
          this.pendingRequestFetch = null;
          resolve(msg.request);
        }
        break;
      case "executeRequest":
        // msg.savedRequest is the original state (no injected auth headers) — used for history.
        await this.requestExecutor.execute(msg.request, msg.savedRequest, msg.tabId);
        break;
      case "getOAuthToken":
        await this._handleGetOAuthToken(msg.config, msg.tabId);
        break;
      case "cancelRequest":
        if (msg.tabId) this.requestExecutor.abortTab(msg.tabId);
        else this.requestExecutor.cancelActive();
        break;
      case "wsConnect":
      case "wsDisconnect":
      case "wsSend":
        this.wsSessions.handleMessage(msg);
        break;
      case "setScriptVariables":
        // Script extracted variables - store them scoped to this window session
        // (Postman-style chaining). Same window → unlimited requests; a new
        // window gets a fresh scope.
        if (this.sessionId) {
          this.storageManager.setSessionChainVars(this.sessionId, msg.variables);
          this._sendSessionChainVars();
        }
        break;
      case "saveToCollection":
        this._saveToCollection(msg.request, msg.collectionName, msg.groupId);
        break;
      case "getCollections":
        this.updateMetadata();
        break;
      case "openSettings":
        vscode.commands.executeCommand(
          "workbench.action.openSettings",
          "restify",
        );
        break;
      case "configureProxy":
        await initializeProxySettings();
        break;
      case "downloadFile":
        await downloadFile(msg.payload);
        break;
      case "saveResponseToFile":
        await saveResponseToFile(msg.payload);
        break;
      case "getEnvironments":
        this._sendEnvironments();
        break;
      case "setActiveEnvironment":
        this.storageManager.setActiveEnvironment(msg.id);
        break;
      case "saveEnvironment": {
        const env = { ...msg.data };
        if (Array.isArray(env.variables)) {
          env.variables = env.variables.filter(
            (v: any) =>
              (v.key || "").toString().trim() !== "" ||
              (v.value || "").toString().trim() !== "",
          );
        }
        await this.storageManager.saveEnvironment(env);
        this._sendEnvironments();
        break;
      }
      case "deleteEnvironment": {
        await this.storageManager.deleteEnvironment(msg.id);
        this._sendEnvironments();
        break;
      }
      case "importEnvironment":
        await this._importEnvironment();
        break;
      case "exportEnvironment":
        await this._exportEnvironment(msg.env);
        break;
      case "getEnvSecretValue": {
        const value = await this.storageManager.getSecretValue(
          msg.envId,
          msg.varKey,
        );
        this.panel.webview.postMessage({
          command: "envSecretValue",
          id: msg.id,
          value: value ?? "",
        });
        break;
      }
      case "updateTitle":
        this.panel.title = msg.title || "New Request";
        break;
      case "saveSettings":
        this.storageManager.saveSettings(msg.settings);
        // Sync activity log enabled state
        this.activityProvider?.setEnabled(msg.settings.showActivityLog !== false);
        // Send confirmation back with the saved settings
        this.panel.webview.postMessage({
          command: "loadSettings",
          settings: msg.settings,
        });
        vscode.window.showInformationMessage("✓ Settings saved successfully");
        break;
      case "runScript":
        this.activityProvider?.append("Script started", "Executing post-response script.", "info");
        await this._runScript(msg.script, msg.response, msg.tabId);
        break;
    }
  }

  private async _runScript(script: string, response: any, tabId = "tab-1"): Promise<void> {
    await runScriptAndReport(script, response, tabId, {
      post: (message) => {
        try {
          this.panel.webview.postMessage(message);
        } catch {
          /* panel disposed */
        }
      },
      appendActivity: (title, detail, type) =>
        this.activityProvider?.append(title, detail, type),
      onSetVariables: (variables) =>
        this._handleMessage({ command: "setScriptVariables", variables }),
    });
  }

  private _saveToCollection(
    request: RequestData,
    collectionName: string,
    groupId?: string,
  ): void {
    const collections = this.storageManager.getCollections();
    let col = collections.find((c) => c.name === collectionName);

    if (!col) {
      const newCol = {
        id: Date.now().toString(),
        name: collectionName,
        requests: [],
      };
      this.storageManager.saveCollection(newCol);
      col = this.storageManager
        .getCollections()
        .find((c) => c.name === collectionName);
    }

    if (col) {
      const requestName = request.name || `${request.method} ${request.url}`;

      if (groupId) {
        // Save into a specific folder within the collection
        const requestToSave = {
          ...request,
          name: requestName,
          id: request.id || Date.now().toString(),
        };
        this.storageManager.addRequestToGroup(col.id, groupId, requestToSave);
        vscode.window.showInformationMessage(
          `✓ Saved "${requestName}" in collection "${collectionName}"`,
        );
      } else {
        // Save to collection root
        const existingRequest = col.requests?.find(
          (r) => r.name === requestName,
        );

        const requestToSave = {
          ...request,
          name: requestName,
          id: existingRequest?.id || Date.now().toString(),
        };

        this.storageManager.addRequestToCollection(col.id, requestToSave);

        const action = existingRequest ? "Updated" : "Saved";
        vscode.window.showInformationMessage(
          `✓ ${action} "${requestName}" in collection "${collectionName}"`,
        );
      }
    }
  }
}
